apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediconnect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediconnect
  template:
    metadata:
      labels:
        app: mediconnect
    spec:
      containers:
      - name: mediconnect
        image: vipul710/mediconnect:latest
        ports:
        - containerPort: 3000
